---
version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dupl
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gosec
    - importas
    - ireturn

  settings:
    ireturn:
      allow:
        - error
        - db.Error

run:
  issues-exit-code: 1
